# Setup
title:               PJH’s BLOG
tagline:             '이런저런 노하우 공유용 블로그!'
description:         '이런저런 노하우 공유용 블로그!'
url:                 http://junhyungpark78.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Park Junhyung
  url:               https://jidae.com
  email:             parkjh78@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Build settings
timezone: Asia/Tokyo

# Disqus comments
disqus_shortname:    "Park Junhyung"

# Custom vars
version:             1.1.0
google_analytics_id: "UA-125021765-1"

